### ISSUE TITLE
AILint won't automatically analyze local diff

### ISSUE THREAD

**Issue by XiaoningDing** [bd-iaas-us/AILint#39]
What happened:
 * AILint asks me to specific a file name
 
What happened:
* When under a git folder and there are local changes, it should automatically analyze the diff

See the screenshot:
 
<img width="531" alt="image" src="https://github.com/bd-iaas-us/AILint/assets/16261467/cfacd9a2-5515-4c16-be08-16bebed69e51">

**Comment by thesues** [comment]
fixed
